# Generated by Django 2.2 on 2020-10-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalpersonnel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
