# Generated by Django 2.2 on 2020-10-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientMonitor', '0002_hospitalpersonnel_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(blank=True)),
                ('sex', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=10)),
                ('Blood_Group', models.CharField(choices=[(1, 'O-'), (2, 'O+'), (3, 'A-'), (4, 'A+'), (5, 'B-'), (6, 'B+'), (7, 'AB-'), (4, 'AB+')], max_length=5)),
                ('Weight', models.FloatField(blank=True)),
                ('Height', models.IntegerField(blank=True)),
                ('Phone_No', models.CharField(blank=True, max_length=14, unique=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
