# Generated by Django 2.2 on 2020-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0003_patient_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_registration',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.AlterField(
            model_name='patient_registration',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
