# Generated by Django 2.2 on 2020-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0004_auto_20201014_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='Blood_Group',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=5),
        ),
    ]
