# Generated by Django 2.2 on 2020-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0005_auto_20201014_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_registration',
            old_name='Patient',
            new_name='user',
        ),
    ]
