# Generated by Django 2.2 on 2020-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0007_doctor_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='Hospital_Name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
