# Generated by Django 2.2 on 2020-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0008_doctor_registration_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='Bed_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='Room_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='Ward_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
