# Generated by Django 2.2 on 2020-10-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0010_auto_20201015_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_registration',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='demo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientMonitor.Demo'),
        ),
    ]
