# Generated by Django 2.2 on 2020-10-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0011_auto_20201015_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='demo',
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='doctor_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientMonitor.doctor_registration'),
        ),
    ]
