# Generated by Django 2.2 on 2020-10-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0012_auto_20201015_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_registration',
            old_name='doctor_registration',
            new_name='doctor',
        ),
    ]
