# Generated by Django 2.2 on 2020-10-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0013_auto_20201015_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(blank=True)),
                ('Pulse_Rate', models.IntegerField(blank=True)),
                ('Oxygen_Saturation', models.IntegerField(blank=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientMonitor.patient_registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
