# Generated by Django 2.2 on 2020-10-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0016_auto_20201016_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_registration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
