# Generated by Django 2.2 on 2020-10-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0018_auto_20201016_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_data',
        ),
    ]
