# Generated by Django 2.2 on 2020-10-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0020_temperature_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulse_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pulse_Rate', models.IntegerField(blank=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientMonitor.patient_registration')),
            ],
        ),
    ]
