# Generated by Django 2.2 on 2020-10-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0021_pulse_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='oximeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oxygen_Saturation', models.IntegerField(blank=True)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientMonitor.patient_registration')),
            ],
        ),
    ]
