# Generated by Django 2.2 on 2020-10-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0022_oximeter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulse_sensor',
            name='Patient',
        ),
        migrations.DeleteModel(
            name='oximeter',
        ),
        migrations.DeleteModel(
            name='pulse_sensor',
        ),
    ]
