# Generated by Django 2.2 on 2020-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0023_auto_20201016_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_sensor',
            name='Patient',
            field=models.ManyToManyField(related_name='temperature_list', to='patientMonitor.patient_registration'),
        ),
    ]
