# Generated by Django 2.2 on 2020-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0024_auto_20201016_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulse_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pulse_Rate', models.IntegerField(blank=True)),
                ('Patient', models.ManyToManyField(related_name='pulse_rate_list', to='patientMonitor.patient_registration')),
            ],
        ),
        migrations.CreateModel(
            name='oximeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oxygen_Saturation', models.IntegerField(blank=True)),
                ('Patient', models.ManyToManyField(to='patientMonitor.patient_registration')),
            ],
        ),
    ]
