# Generated by Django 2.2 on 2020-10-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0025_oximeter_pulse_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='oximeter',
            name='Patient',
            field=models.ManyToManyField(related_name='oxygen_saturation_list', to='patientMonitor.patient_registration'),
        ),
    ]
