# Generated by Django 2.2 on 2020-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0027_auto_20201018_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='randomPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='randomdata',
            name='rPatient',
            field=models.ManyToManyField(related_name='rPatient_list', to='patientMonitor.randomPatient'),
        ),
    ]
