# Generated by Django 2.2 on 2020-10-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0028_auto_20201018_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='randomData',
        ),
        migrations.DeleteModel(
            name='randomPatient',
        ),
    ]
