# Generated by Django 2.2 on 2020-10-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0029_auto_20201018_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='slug',
            field=models.SlugField(max_length=1264, null=True, unique=True),
        ),
    ]
