# Generated by Django 2.2 on 2020-10-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0032_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_list', to='patientMonitor.doctor_registration'),
        ),
    ]
