# Generated by Django 2.2 on 2020-10-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0033_auto_20201019_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.AddField(
            model_name='prescription',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescription', to='patientMonitor.doctor_registration'),
        ),
    ]
