# Generated by Django 2.2 on 2020-10-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0034_auto_20201019_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Normal', 'Normal')], max_length=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_stat', to='patientMonitor.patient_registration')),
            ],
        ),
    ]
