# Generated by Django 2.2 on 2020-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0035_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='Status',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Normal', 'Normal')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='patient_status',
        ),
    ]
