# Generated by Django 2.2 on 2020-10-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0036_auto_20201020_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_registration',
            name='Status',
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='Department',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Gynecology', 'Gynecology')], max_length=10, null=True),
        ),
    ]
