# Generated by Django 2.2 on 2020-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0037_auto_20201022_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('Pulse_Rate', models.IntegerField(blank=True, null=True)),
                ('Oxygen_Saturation', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pulse_sensor',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='temperature_sensor',
            name='Patient',
        ),
        migrations.AlterField(
            model_name='patient_registration',
            name='Department',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Gynecology', 'Gynecology')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='oximeter',
        ),
        migrations.DeleteModel(
            name='pulse_sensor',
        ),
        migrations.DeleteModel(
            name='temperature_sensor',
        ),
        migrations.AddField(
            model_name='sensors',
            name='Patient',
            field=models.ManyToManyField(related_name='sensors_list', to='patientMonitor.patient_registration'),
        ),
    ]
