# Generated by Django 2.2 on 2020-10-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0038_auto_20201023_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='Patient',
        ),
        migrations.AddField(
            model_name='sensors',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors_list', to='patientMonitor.patient_registration'),
        ),
    ]
