# Generated by Django 2.2 on 2020-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0039_auto_20201023_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_registration',
            name='Category',
        ),
        migrations.AddField(
            model_name='doctor_registration',
            name='Department',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Gynecology', 'Gynecology')], max_length=50, null=True),
        ),
    ]
