# Generated by Django 2.2 on 2020-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0040_auto_20201023_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='call',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
