# Generated by Django 2.2 on 2020-10-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0041_sensors_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='Monitoring',
            field=models.CharField(blank=True, choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Gynecology', 'Gynecology')], max_length=50, null=True),
        ),
    ]
