# Generated by Django 2.2 on 2020-10-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0042_patient_registration_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='Monitoring',
            field=models.CharField(blank=True, choices=[('Hospital', 'Hospital'), ('Home', 'Home')], max_length=50, null=True),
        ),
    ]
