# Generated by Django 2.2 on 2020-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0043_auto_20201026_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(blank=True, max_length=200)),
                ('Contact_No', models.CharField(blank=True, max_length=14)),
                ('Ambulance_No', models.CharField(blank=True, max_length=14, unique=True)),
                ('Hospital_Name', models.CharField(blank=True, max_length=200)),
                ('Availability', models.BooleanField()),
            ],
        ),
    ]
