# Generated by Django 2.2 on 2020-10-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0045_prescription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescription_date', 'user']},
        ),
    ]
