# Generated by Django 2.2 on 2020-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientMonitor', '0047_auto_20201028_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='Phone_No',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
